Print location

diff --git a/bin/lintball b/bin/lintball
--- a/bin/lintball
+++ b/bin/lintball
@@ -24,7 +24,8 @@ elif [ -d "${BIN_DIR}/../node_modules/lintball/configs/lintballrc-defaults.json"
     pwd
   )"
 else
-  echo "Cannot find lintball installation" >&2
+  echo "Cannot find lintball installation from ${BASH_SOURCE[0]}" >&2
+  find "$BIN_DIR/.."
   exit 1
 fi
 
