Uncrustify (#1)
* Simplify gitignore

* Reorganize directory structure

* Update bats-assert ref

* Update bats-assert ref

* Fix unbound var error in install.sh

* Remove class/jar

* Create a temp tag for testing

* Fix tagging

* Fix test

* fix link

* Add bats shellcheck support

* Fix test linting

* Fix JS tests

* Add uncrustify tests, separate configs per language

* Add c# support

* Fix tests

* Fix lint job

* Re-source after git repo update

* Fix tests

* Rename some things

* Fix formatting of Java/C#

* a bunch more formatters, better test coverage

* Install rust deps

* Fix missing path issue, add tests

* Use AirBnB eslint config

* Fix JS tests

* Fix clippy

* Install via npm

* Simplify pre-commit

* Fix install-githooks tests

* Fix pre-commit tests

* Refactor and cleanup

* Add apt/pacman support

* Remove empty test file

* Alpine support

* Install correct ruby

* Swap action

* Refactor workflow

* Fix tool installation

* Debug

* Debug

* Debug

* Debug

* Fix path detection

* Cleanup installer

* Syntax error fix?

* nim install fix

* Print location

* syntax

* Fix

* debug

* Fix global

* bash

* fix project_dir

* Fix lint

* Variable scope

* Debug

* thing

* Fix bug

* Bug

* Fix path

* Remove debugging

* version check for shellcheck

* Debug

* Debug

* Disable for now

* Don’t use stdin

* Sudo if necessary

* Install wheel

* permissions

* Try variant of regex

* Fix -u usage

* Fix packages

* Re-enable jobs

* Fix test

* Fix tests

* Fix test

diff --git a/bin/lintball b/bin/lintball
--- a/bin/lintball
+++ b/bin/lintball
@@ -2,12 +2,34 @@
 
 set -ueo pipefail
 
-LINTBALL_DIR="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"
+# path to node_modules/.bin
+BIN_DIR="$(dirname "${BASH_SOURCE[0]}")"
 
-# shellcheck source=SCRIPTDIR/../lib/utils.bash
-source "${LINTBALL_DIR}/lib/utils.bash"
+if [ -f "${BIN_DIR}/../configs/lintballrc-defaults.json" ]; then
+  # path to repo
+  LINTBALL_DIR="$(
+    cd "${BIN_DIR}/.."
+    pwd
+  )"
+elif [ -f "${BIN_DIR}/../lintball/configs/lintballrc-defaults.json" ]; then
+  # path to installation via npm, local
+  LINTBALL_DIR="$(
+    cd "${BIN_DIR}/../lintball"
+    pwd
+  )"
+elif [ -f "${BIN_DIR}/../lib/node_modules/lintball/configs/lintballrc-defaults.json" ]; then
+  # path to installation via npm, global
+  LINTBALL_DIR="$(
+    cd "${BIN_DIR}/../lib/node_modules/lintball"
+    pwd
+  )"
+else
+  echo "Cannot find lintball installation from ${BASH_SOURCE[0]}" >&2
+  find "$BIN_DIR/.."
+  exit 1
+fi
 
-# Load default config
-load_config "${LINTBALL_DIR}/configs/lintballrc.json"
+# shellcheck source=SCRIPTDIR/../lib/cli.bash
+source "${LINTBALL_DIR}/lib/cli.bash"
 
-parse_args "$@"
+cli_entrypoint "$@" || exit $?
