Fix test

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -5,21 +5,31 @@ set -ueo pipefail
 # path to node_modules/.bin
 BIN_DIR="$(dirname "${BASH_SOURCE[0]}")"
 
-if [ "$(basename "$BIN_DIR")" = ".bin" ]; then
-  # path to node_modules/lintball
-  LINTBALL_DIR="$(
-    cd "${BIN_DIR}/../lintball"
-    pwd
-  )"
-else
+if [ -f "${BIN_DIR}/../configs/lintballrc-defaults.json" ]; then
   # path to repo
   LINTBALL_DIR="$(
     cd "${BIN_DIR}/.."
     pwd
   )"
+elif [ -f "${BIN_DIR}/../lintball/configs/lintballrc-defaults.json" ]; then
+  # path to installation via npm, local
+  LINTBALL_DIR="$(
+    cd "${BIN_DIR}/../lintball"
+    pwd
+  )"
+elif [ -f "${BIN_DIR}/../lib/node_modules/lintball/configs/lintballrc-defaults.json" ]; then
+  # path to installation via npm, global
+  LINTBALL_DIR="$(
+    cd "${BIN_DIR}/../lib/node_modules/lintball"
+    pwd
+  )"
+else
+  echo "Cannot find lintball installation from ${BASH_SOURCE[0]}" >&2
+  find "$BIN_DIR/.."
+  exit 1
 fi
 
-# shellcheck source=SCRIPTDIR/../lib/cli.bash
+# shellcheck disable=SC1090,SC1091
 source "${LINTBALL_DIR}/lib/cli.bash"
 
 cli_entrypoint pre-commit || exit $?
