workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -105,8 +105,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
+        with:
+          driver-opts: network=host
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -114,24 +119,86 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build
-        run: ./build-docker.bash --single-arch amd64
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build amd64
+        run: |
+          docker buildx build \
+            --progress=plain \
+            --build-arg="DEBIAN_VERSION=bullseye" \
+            --build-arg="TESTING=yes" \
+            --platform linux/amd64 \
+            --push \
+            --tag localhost:5000/elijahru/lintball \
+            .
+
+      - name: Build all
+        run: |
+          docker buildx build \
+            --progress=plain \
+            --build-arg="DEBIAN_VERSION=bullseye" \
+            --build-arg="TESTING=yes" \
+            --platform linux/amd64,linux/arm64 \
+            --push \
+            --tag localhost:5000/elijahru/lintball \
+            .
 
       - name: Lint
         # Lint lintball with lintball
         run: |
-          export LINTBALL_IMAGE_TAG="latest-amd64"
           export LINTBALL_WORKSPACE="${{ github.workspace }}"
-          docker-compose run lintball
+          docker-compose run lint
 
       - name: Test
         # Run tests in built docker
         run: |
-          export LINTBALL_IMAGE_TAG="latest-amd64"
           export LINTBALL_WORKSPACE="${{ github.workspace }}"
           docker-compose run test
 
+      # - name: Build arm64
+      #   run: |
+      #     docker buildx build \
+      #       --build-arg="DEBIAN_VERSION=bullseye" \
+      #       --build-arg="TESTING=yes" \
+      #       --platform linux/amd64,linux/arm64 \
+      #       --push \
+      #       --cache-from=localhost:5000/elijahr/lintball \
+      #       --tag localhost:5000/elijahru/lintball \
+      #       .
+
       - name: Push to DockerHub
         # Only for git tag pushes; build arm64 and push all images to DockerHub
-        if: ${{ startsWith(github.ref, 'refs/tags/') }}
-        run: ./build-docker.bash --push
+        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
+        shell: bash
+        run: |
+          set -uexo pipefail
+
+          if [[ -n $(command -v jq) ]]; then
+            version=$(jq -r .version ./package.json)
+          elif [[ -n $(command -v npm) ]]; then
+            # shellcheck disable=SC2016
+            version=$(npm -s run env echo '$npm_package_version')
+          else
+            echo >&2
+            echo "Could not find jq or npm. Please install one of them." >&2
+            exit 1
+          fi
+          major_version=$(echo "${version}" | awk -F '.' '{print $1}')
+          minor_version=$(echo "${version}" | awk -F '.' '{print $2}')
+
+          declare -a tags=("latest" "${major}" "${major.minor}" "${version}")
+          for tag in "${tags[@]}"; do
+            docker buildx build \
+              --build-arg="DEBIAN_VERSION=bullseye" \
+              --build-arg="TESTING=yes" \
+              --platform linux/amd64 \
+              --push \
+              --cache-from=localhost:5000/elijahr/lintball \
+              --tag "docker.io/elijahru/lintball:${tag}" \
+              .
+          done
